# Generated by Django 4.0.2 on 2022-06-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_related_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tedad',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
